### ISSUE TITLE
Wiki и README отсутсвуют

### ISSUE THREAD

**Issue by davidkirakosyan** [davidkirakosyan/tide_rep#4]
Нужно писать хотя бы один из Wiki или Readme. Нужно прописать какие невстроенные библиотеки используются, на каких Оперативных Системах работает. @TaisiiaKarasova

**Comment by TaisiiaKarasova** [comment]
@davidkirakosyan сделала README

**Comment by TaisiiaKarasova** [comment]
wiki is ready
