### ISSUE TITLE
Невозможно перетаскивать объекты в режиме паузы

### ISSUE THREAD

**Issue by TaisiiaKarasova** [davidkirakosyan/tide_rep#7]
После добавления возможности перетаскивать бекграунд стало невозможно ничего перетаскивать в режиме паузы

**Comment by davidkirakosyan** [comment]
Проблема в том, что при перетаскивании холста, экран не обновляется.

**Comment by davidkirakosyan** [comment]
В 0f2652f4 уже исправлено. Создал метод Window.update_screen(), где обновляются объекты, если программа в режиме паузы
